name: Architect Production Deployment

on:
  release:
    types:
      - published

env:
  ARCHITECT_GENERATED: true
  ARCHITECT_PRODUCTION: true
  COMPONENT_FILE_PATH: architect.yml
  ACCOUNT_NAME: muesch
  COMPONENT_NAME: hello-world
  ENVIRONMENT_NAME: example-environment

jobs:
  architect_create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Architect CLI
        run: sudo npm install -g @architect-io/cli
      - name: Login to Architect Cloud
        run: architect login -e ${{ secrets.ARCHITECT_EMAIL }} -p ${{ secrets.ARCHITECT_PASSWORD }}
      - name: Register component w/ Architect
        run: architect register ${{ env.COMPONENT_FILE_PATH }} -t latest
      - name: Deploy component
        run: architect deploy --auto-approve -a ${{ env.ACCOUNT_NAME }} -e ${{ env.ENVIRONMENT_NAME }} ${{ env.COMPONENT_NAME }}:latest
